// Datos del catalogo Grupo Cenepena Malaga. Editar aqui para agregar/quitar/renombrar productos.
// Productos sin foto usan img/sin-foto.jpg: al tener la foto, subirla como img/<id>.jpg y cambiar su "img".
const WA="34644511533";

const CATS=[["harinas", "Almidón y harinas"], ["granos", "Granos"], ["pastas", "Pasta"], ["yerba", "Yerba mate"], ["platanitos", "Platanitos y snacks"], ["especias", "Especias, hierbas y condimentos"], ["salsas", "Salsas"], ["dulces", "Galletas y dulces"], ["frutos", "Frutos secos"], ["menaje", "Menaje"]];

const PRODUCTS=[
  {"id": "almidon_agrio_codipsa_25kg", "n": "Almidón Agrio Codipsa", "c": "harinas", "f": "Saco 25 kg", "d": "Almidón agrio de mandioca Codipsa, formato saco.", "img": "img/almidon_agrio_codipsa_25kg.jpg"},
  {"id": "almidon_chipero_premium_25kg", "n": "Almidón Chipero Premium Codipsa", "c": "harinas", "f": "Saco 25 kg", "d": "Almidón chipero premium para chipa, formato saco.", "img": "img/almidon_chipero_premium_25kg.jpg"},
  {"id": "almidon_chipero_premium_1kg", "n": "Almidón Chipero Premium Codipsa", "c": "harinas", "f": "1 kg", "d": "Almidón chipero premium para chipa.", "img": "img/almidon_chipero_premium_1kg.jpg"},
  {"id": "almidon_chipero_tradicional_25kg", "n": "Almidón Chipero Tradicional Codipsa", "c": "harinas", "f": "Saco 25 kg", "d": "Almidón chipero tradicional, formato saco.", "img": "img/almidon_chipero_tradicional_25kg.jpg"},
  {"id": "almidon_chipero_tradicional_1kg", "n": "Almidón Chipero Tradicional Codipsa", "c": "harinas", "f": "1 kg", "d": "Almidón chipero tradicional para chipa.", "img": "img/almidon_chipero_tradicional_1kg.jpg"},
  {"id": "almidon_maiz_codipsa_25kg", "n": "Almidón de Maíz Codipsa", "c": "harinas", "f": "Saco 25 kg", "d": "Almidón de maíz Codipsa, formato saco.", "img": "img/almidon_maiz_codipsa_25kg.jpg"},
  {"id": "almidon_dulce_codipsa_10x1kg", "n": "Almidón Dulce Codipsa", "c": "harinas", "f": "10 x 1 kg", "d": "Almidón dulce de mandioca Codipsa.", "img": "img/almidon_dulce_codipsa_10x1kg.jpg"},
  {"id": "almidon_dulce_codipsa_25kg", "n": "Almidón Dulce Codipsa", "c": "harinas", "f": "Saco 25 kg", "d": "Almidón dulce de mandioca Codipsa, formato saco.", "img": "img/almidon_dulce_codipsa_25kg.jpg"},
  {"id": "almidon_selecta_1kg", "n": "Almidón Selecta", "c": "harinas", "f": "1 kg", "d": "Almidón de mandioca Selecta.", "img": "img/almidon_selecta_1kg.jpg"},
  {"id": "almidon_selecta_24x500g", "n": "Almidón Selecta", "c": "harinas", "f": "24 x 500 g", "d": "Almidón de mandioca Selecta.", "img": "img/almidon_selecta_24x500g.jpg"},
  {"id": "harina_maiz_intertropico", "n": "Harina de Maíz Intertropico", "c": "harinas", "f": "15 x 1 kg", "d": "Harina de maíz precocida Intertropico.", "img": "img/harina_maiz_intertropico.jpg"},
  {"id": "soja_torrada_arcoiris", "n": "Soja Torrada Arcoiris", "c": "harinas", "f": "250 g", "d": "Harina de soja torrada Arcoiris.", "img": "img/soja_torrada_arcoiris.jpg"},
  {"id": "harina_pan_amarilla", "n": "Harina P.A.N. Amarilla", "c": "harinas", "f": "10 x 1 kg", "d": "Harina de maíz amarillo precocida P.A.N.", "img": "img/harina_pan_amarilla.jpg"},
  {"id": "harina_pan_blanca", "n": "Harina P.A.N. Blanca", "c": "harinas", "f": "10 x 1 kg", "d": "Harina de maíz blanco precocida P.A.N.", "img": "img/harina_pan_blanca.jpg"},
  {"id": "harina_pan_dulce", "n": "Harina P.A.N. Dulce", "c": "harinas", "f": "18 x 500 g", "d": "Harina de maíz dulce P.A.N. para cachapas.", "img": "img/harina_pan_dulce.jpg"},
  {"id": "premezcla_pizza_codipsa", "n": "Premezcla para Pizza Codipsa", "c": "harinas", "f": "50 x 500 g", "d": "Premezcla lista para preparar masa de pizza.", "img": "img/premezcla_pizza_codipsa.jpg"},
  {"id": "premezcla_mbeju_codipsa", "n": "Premezcla Mbeju Codipsa", "c": "harinas", "f": "50 x 500 g", "d": "Premezcla para mbeju paraguayo.", "img": "img/premezcla_mbeju_codipsa.jpg"},
  {"id": "pandeyuca_colmaiz", "n": "Premezcla Pandeyuca Colmaiz", "c": "harinas", "f": "Paquete", "d": "Premezcla para pan de yuca Colmaiz.", "img": "img/pandeyuca_colmaiz.jpg"},
  {"id": "tapioca_da_terrinha", "n": "Tapioca Da Terrinha", "c": "harinas", "f": "500 g", "d": "Goma de tapioca Da Terrinha.", "img": "img/tapioca_da_terrinha.jpg"},
  {"id": "cernido_guayaba_levapan", "n": "Cernido de Guayaba Levapan", "c": "harinas", "f": "Caja 5 kg", "d": "Cernido de guayaba Levapan para repostería.", "img": "img/cernido_guayaba_levapan.jpg"},
  {"id": "almidon_agrio_codipsa_1kg", "n": "Almidón Agrio Codipsa", "c": "harinas", "f": "1 kg", "d": "Almidón agrio de mandioca Codipsa.", "img": "img/sin-foto.jpg"},
  {"id": "mazamorra_amarilla_america", "n": "Mazamorra Amarilla América", "c": "granos", "f": "24 x 500 g", "d": "Maíz amarillo para mazamorra América.", "img": "img/mazamorra_amarilla_america.jpg"},
  {"id": "maiz_tostar_cancha_america", "n": "Maíz de Tostar Cancha América", "c": "granos", "f": "24 x 500 g", "d": "Maíz cancha para tostar América.", "img": "img/maiz_tostar_cancha_america.jpg"},
  {"id": "maiz_morocho_plebeyo", "n": "Maíz Morocho El Plebeyo", "c": "granos", "f": "24 x 500 g", "d": "Maíz morocho El Plebeyo.", "img": "img/maiz_morocho_plebeyo.jpg"},
  {"id": "frijol_negro_do_brasil", "n": "Frijol Negro Do Brasil", "c": "granos", "f": "10 x 1 kg", "d": "Feijão / frijol negro Do Brasil.", "img": "img/frijol_negro_do_brasil.jpg"},
  {"id": "maiz_mote_america", "n": "Maíz Mote América", "c": "granos", "f": "24 x 500 g", "d": "Maíz mote América.", "img": "img/maiz_mote_america.jpg"},
  {"id": "maiz_trillado_blanco_el_dorado", "n": "Maíz Trillado Blanco El Dorado", "c": "granos", "f": "15 x 1 kg", "d": "Maíz blanco trillado El Dorado.", "img": "img/maiz_trillado_blanco_el_dorado.jpg"},
  {"id": "poroto_selecta_vacio", "n": "Poroto Selecta al Vacío", "c": "granos", "f": "16 x 500 g", "d": "Poroto Selecta envasado al vacío.", "img": "img/poroto_selecta_vacio.jpg"},
  {"id": "frijol_rojo_seda_as_de_oro", "n": "Frijol Rojo de Seda As de Oro", "c": "granos", "f": "Paquete", "d": "Frijol rojo de seda As de Oro.", "img": "img/frijol_rojo_seda_as_de_oro.jpg"},
  {"id": "mazamorra_blanca_america", "n": "Mazamorra Blanca América", "c": "granos", "f": "24 x 500 g", "d": "Maíz blanco para mazamorra América.", "img": "img/mazamorra_blanca_america.jpg"},
  {"id": "locrillo_arcoiris", "n": "Locrillo Arcoiris", "c": "granos", "f": "400 g", "d": "Locrillo Arcoiris.", "img": "img/locrillo_arcoiris.jpg"},
  {"id": "locro_arcoiris", "n": "Locro Arcoiris", "c": "granos", "f": "400 g", "d": "Maíz para locro Arcoiris.", "img": "img/locro_arcoiris.jpg"},
  {"id": "fideo_cortadito_napoli", "n": "Fideos Cortadito Napoli", "c": "pastas", "f": "Paquete", "d": "Fideos cortadito Napoli.", "img": "img/fideo_cortadito_napoli.jpg"},
  {"id": "espaguetis_campo9", "n": "Fideos Espaguetis Campo9", "c": "pastas", "f": "10 x 400 g", "d": "Espaguetis Campo9.", "img": "img/espaguetis_campo9.jpg"},
  {"id": "fideo_monitos_napoli", "n": "Fideos Moñitos Amarillo Napoli", "c": "pastas", "f": "10 x 400 g", "d": "Fideos moñitos amarillos Napoli.", "img": "img/fideo_monitos_napoli.jpg"},
  {"id": "tallarin_campo9", "n": "Fideos Tallarín Campo9", "c": "pastas", "f": "10 x 400 g", "d": "Tallarines Campo9.", "img": "img/tallarin_campo9.jpg"},
  {"id": "spaguetti_napoli", "n": "Spaguetti Napoli", "c": "pastas", "f": "400 g", "d": "Spaguetti Napoli.", "img": "img/spaguetti_napoli.jpg"},
  {"id": "tallarin_amarillo_napoli", "n": "Tallarín Amarillo Napoli", "c": "pastas", "f": "10 x 400 g", "d": "Tallarín amarillo Napoli.", "img": "img/tallarin_amarillo_napoli.jpg"},
  {"id": "kurupi_compuesta_menta_boldo", "n": "Yerba Kurupí Compuesta Menta y Boldo", "c": "yerba", "f": "12 x 500 g", "d": "Yerba mate compuesta Kurupí con menta y boldo.", "img": "img/kurupi_compuesta_menta_boldo.jpg"},
  {"id": "indega_fresca", "n": "Yerba Indega Fresca", "c": "yerba", "f": "10 x 500 g", "d": "Yerba mate Indega Fresca.", "img": "img/indega_fresca.jpg"},
  {"id": "indega_manzanilla_anis", "n": "Yerba Indega Manzanilla y Anís", "c": "yerba", "f": "10 x 500 g", "d": "Yerba mate Indega con manzanilla y anís.", "img": "img/indega_manzanilla_anis.jpg"},
  {"id": "indega_menta_boldo", "n": "Yerba Indega Menta y Boldo", "c": "yerba", "f": "10 x 500 g", "d": "Yerba mate Indega con menta y boldo.", "img": "img/indega_menta_boldo.jpg"},
  {"id": "kurupi_anis", "n": "Yerba Kurupí Anís", "c": "yerba", "f": "12 x 500 g", "d": "Yerba mate Kurupí con anís.", "img": "img/kurupi_anis.jpg"},
  {"id": "kurupi_katuava_burrito", "n": "Yerba Kurupí Katuava y Burrito", "c": "yerba", "f": "12 x 500 g", "d": "Yerba mate Kurupí con katuava y burrito.", "img": "img/kurupi_katuava_burrito.jpg"},
  {"id": "kurupi_yorador", "n": "Yerba Kurupí Yorador", "c": "yerba", "f": "12 x 500 g", "d": "Yerba mate Kurupí Yorador.", "img": "img/kurupi_yorador.jpg"},
  {"id": "selecta_doble_sabor", "n": "Yerba Selecta Doble Sabor", "c": "yerba", "f": "10 x 500 g", "d": "Yerba mate Selecta Doble Sabor.", "img": "img/selecta_doble_sabor.jpg"},
  {"id": "selecta_siempre_mate", "n": "Yerba Selecta Siempre Mate", "c": "yerba", "f": "10 x 500 g", "d": "Yerba mate Selecta Siempre Mate.", "img": "img/selecta_siempre_mate.jpg"},
  {"id": "selecta_silueta", "n": "Yerba Selecta Silueta", "c": "yerba", "f": "10 x 500 g", "d": "Yerba mate Selecta Silueta.", "img": "img/selecta_silueta.jpg"},
  {"id": "selecta_tradicional", "n": "Yerba Selecta Tradicional", "c": "yerba", "f": "10 x 500 g", "d": "Yerba mate Selecta Tradicional.", "img": "img/selecta_tradicional.jpg"},
  {"id": "indega_pantano_limon", "n": "Yerba Indega Pantano Limón", "c": "yerba", "f": "10 x 500 g", "d": "Yerba Indega Pantano con limón.", "img": "img/indega_pantano_limon.jpg"},
  {"id": "cbse_frutas_bosque", "n": "Yerba CBSé Frutas del Bosque", "c": "yerba", "f": "500 g", "d": "Yerba mate CBSé sabor frutas del bosque.", "img": "img/cbse_frutas_bosque.jpg"},
  {"id": "cbse_guarana", "n": "Yerba CBSé Guaraná", "c": "yerba", "f": "500 g", "d": "Yerba mate CBSé con guaraná.", "img": "img/cbse_guarana.jpg"},
  {"id": "cbse_hierbas_serranas_500g", "n": "Yerba CBSé Hierbas Serranas", "c": "yerba", "f": "12 x 500 g", "d": "Yerba mate CBSé con hierbas serranas.", "img": "img/cbse_hierbas_serranas_500g.jpg"},
  {"id": "cbse_limon", "n": "Yerba CBSé Limón", "c": "yerba", "f": "500 g", "d": "Yerba mate CBSé sabor limón.", "img": "img/cbse_limon.jpg"},
  {"id": "cbse_naranja", "n": "Yerba CBSé Naranja", "c": "yerba", "f": "500 g", "d": "Yerba mate CBSé sabor naranja.", "img": "img/cbse_naranja.jpg"},
  {"id": "canarias_1kg", "n": "Yerba Mate Canarias", "c": "yerba", "f": "1 kg", "d": "Yerba mate Canarias.", "img": "img/canarias_1kg.jpg"},
  {"id": "canarias_500g", "n": "Yerba Mate Canarias", "c": "yerba", "f": "500 g", "d": "Yerba mate Canarias.", "img": "img/canarias_500g.jpg"},
  {"id": "cbse_pomelo", "n": "Yerba CBSé Pomelo", "c": "yerba", "f": "500 g", "d": "Yerba mate CBSé sabor pomelo.", "img": "img/cbse_pomelo.jpg"},
  {"id": "indega_clasica", "n": "Yerba Indega Clásica", "c": "yerba", "f": "10 x 500 g", "d": "Yerba mate Indega Clásica.", "img": "img/indega_clasica.jpg"},
  {"id": "pajarito_compuesta", "n": "Yerba Pajarito Compuesta con Hierbas", "c": "yerba", "f": "20 x 500 g", "d": "Yerba mate Pajarito compuesta con hierbas.", "img": "img/pajarito_compuesta.jpg"},
  {"id": "pajarito_especial", "n": "Yerba Pajarito Especial", "c": "yerba", "f": "500 g", "d": "Yerba mate Pajarito Especial.", "img": "img/pajarito_especial.jpg"},
  {"id": "pajarito_menta_limon", "n": "Yerba Pajarito Menta Limón", "c": "yerba", "f": "20 x 500 g", "d": "Yerba mate Pajarito con menta y limón.", "img": "img/pajarito_menta_limon.jpg"},
  {"id": "pajarito_tradicional", "n": "Yerba Pajarito Tradicional", "c": "yerba", "f": "500 g", "d": "Yerba mate Pajarito Tradicional.", "img": "img/pajarito_tradicional.jpg"},
  {"id": "nobleza_gaucha", "n": "Yerba Nobleza Gaucha", "c": "yerba", "f": "500 g", "d": "Yerba mate Nobleza Gaucha.", "img": "img/nobleza_gaucha.jpg"},
  {"id": "selecta_limon", "n": "Yerba Selecta Limón", "c": "yerba", "f": "10 x 500 g", "d": "Yerba mate Selecta con limón.", "img": "img/selecta_limon.jpg"},
  {"id": "kurupi_fit", "n": "Yerba Kurupí Fit", "c": "yerba", "f": "500 g", "d": "Yerba mate Kurupí Fitness.", "img": "img/kurupi_fit.jpg"},
  {"id": "kurupi_jengibre", "n": "Yerba Kurupí Jengibre", "c": "yerba", "f": "12 x 500 g", "d": "Yerba mate Kurupí con jengibre.", "img": "img/kurupi_jengibre.jpg"},
  {"id": "campesino_anis", "n": "Yerba Campesino Anís", "c": "yerba", "f": "10 x 500 g", "d": "Yerba mate Campesino con anís.", "img": "img/campesino_anis.jpg"},
  {"id": "campesino_katuava", "n": "Yerba Campesino Katuava Energizante", "c": "yerba", "f": "10 x 500 g", "d": "Yerba mate Campesino con katuava.", "img": "img/campesino_katuava.jpg"},
  {"id": "campesino_mbarete", "n": "Yerba Campesino Mbareté", "c": "yerba", "f": "10 x 500 g", "d": "Yerba mate Campesino Mbareté.", "img": "img/campesino_mbarete.jpg"},
  {"id": "campesino_menta_limon", "n": "Yerba Campesino Menta y Limón", "c": "yerba", "f": "10 x 500 g", "d": "Yerba mate Campesino con menta y limón.", "img": "img/campesino_menta_limon.jpg"},
  {"id": "campesino_refrescante", "n": "Yerba Campesino Refrescante", "c": "yerba", "f": "10 x 500 g", "d": "Yerba mate Campesino Refrescante.", "img": "img/campesino_refrescante.jpg"},
  {"id": "campesino_hierbas_naturales", "n": "Yerba Campesino Tradicional Hierbas Naturales", "c": "yerba", "f": "10 x 500 g", "d": "Yerba mate Campesino con hierbas naturales.", "img": "img/campesino_hierbas_naturales.jpg"},
  {"id": "campesino_fitness", "n": "Yerba Campesino Fitness", "c": "yerba", "f": "10 x 500 g", "d": "Yerba mate Campesino Fitness.", "img": "img/campesino_fitness.jpg"},
  {"id": "colon_906090", "n": "Yerba Colón 90-60-90", "c": "yerba", "f": "12 x 500 g", "d": "Yerba mate compuesta Colón 90-60-90.", "img": "img/colon_906090.jpg"},
  {"id": "colon_mate_completo", "n": "Yerba Colón Compuesta Mate Completo", "c": "yerba", "f": "12 x 500 g", "d": "Yerba mate Colón Mate Completo.", "img": "img/colon_mate_completo.jpg"},
  {"id": "colon_menta_boldo", "n": "Yerba Colón Menta y Boldo", "c": "yerba", "f": "12 x 500 g", "d": "Yerba mate Colón con menta y boldo.", "img": "img/colon_menta_boldo.jpg"},
  {"id": "colon_moringa_katuava", "n": "Yerba Colón Moringa Katuava", "c": "yerba", "f": "500 g", "d": "Yerba mate Colón con moringa y katuava.", "img": "img/colon_moringa_katuava.jpg"},
  {"id": "colon_stevia", "n": "Yerba Colón Stevia", "c": "yerba", "f": "12 x 500 g", "d": "Yerba mate Colón con stevia.", "img": "img/colon_stevia.jpg"},
  {"id": "cbse_hierbas_serranas_1kg", "n": "Yerba CBSé Hierbas Serranas", "c": "yerba", "f": "1 kg", "d": "Yerba mate CBSé con hierbas serranas.", "img": "img/cbse_hierbas_serranas_1kg.jpg"},
  {"id": "kurupi_kapii_cedron", "n": "Yerba Kurupí Kapi'i Cedrón", "c": "yerba", "f": "500 g", "d": "Yerba mate Kurupí con kapi'i cedrón.", "img": "img/kurupi_kapii_cedron.jpg"},
  {"id": "kurupi_mega_menta", "n": "Yerba Kurupí Mega Menta", "c": "yerba", "f": "Caja 12 u.", "d": "Yerba mate Kurupí Mega Menta.", "img": "img/kurupi_mega_menta.jpg"},
  {"id": "kurupi_menta_limon", "n": "Yerba Kurupí Menta Limón", "c": "yerba", "f": "500 g", "d": "Yerba mate Kurupí con menta y limón.", "img": "img/kurupi_menta_limon.jpg"},
  {"id": "platanitos_chile_limon", "n": "Platanitos Chile Limón El Dorado", "c": "platanitos", "f": "30 uds.", "d": "Chips de plátano sabor chile y limón.", "img": "img/platanitos_chile_limon.jpg"},
  {"id": "platanitos_limon", "n": "Platanitos con Limón El Dorado", "c": "platanitos", "f": "30 uds.", "d": "Chips de plátano con limón.", "img": "img/platanitos_limon.jpg"},
  {"id": "platanitos_sal", "n": "Platanitos con Sal El Dorado", "c": "platanitos", "f": "30 uds.", "d": "Chips de plátano con sal.", "img": "img/platanitos_sal.jpg"},
  {"id": "platanitos_dulces", "n": "Platanitos Dulces El Dorado", "c": "platanitos", "f": "30 uds.", "d": "Chips de plátano maduro dulce.", "img": "img/platanitos_dulces.jpg"},
  {"id": "platanitos_picantes", "n": "Platanitos Picantes El Dorado", "c": "platanitos", "f": "30 uds.", "d": "Chips de plátano picantes.", "img": "img/platanitos_picantes.jpg"},
  {"id": "choclitos_limon", "n": "Choclitos Limón El Dorado", "c": "platanitos", "f": "15 x 230 g", "d": "Snack de maíz Choclitos sabor limón.", "img": "img/choclitos_limon.jpg"},
  {"id": "esencia_levapan_banano", "n": "Esencia Levapan Banano", "c": "especias", "f": "24 x 500 ml", "d": "Esencia sabor banano para repostería.", "img": "img/esencia_levapan_banano.jpg"},
  {"id": "esencia_levapan_coco", "n": "Esencia Levapan Coco", "c": "especias", "f": "24 x 500 ml", "d": "Esencia sabor coco para repostería.", "img": "img/esencia_levapan_coco.jpg"},
  {"id": "esencia_levapan_mantequilla", "n": "Esencia Levapan Mantequilla", "c": "especias", "f": "24 x 500 ml", "d": "Esencia sabor mantequilla para repostería.", "img": "img/esencia_levapan_mantequilla.jpg"},
  {"id": "esencia_levapan_ponque", "n": "Esencia Levapan Ponqué", "c": "especias", "f": "24 x 500 ml", "d": "Esencia sabor ponqué para repostería.", "img": "img/esencia_levapan_ponque.jpg"},
  {"id": "esencia_levapan_queso", "n": "Esencia Levapan Queso", "c": "especias", "f": "24 x 500 ml", "d": "Esencia sabor queso para repostería.", "img": "img/esencia_levapan_queso.jpg"},
  {"id": "esencia_levapan_vainilla", "n": "Esencia Levapan Vainilla Blanca", "c": "especias", "f": "24 x 500 ml", "d": "Esencia de vainilla blanca para repostería.", "img": "img/esencia_levapan_vainilla.jpg"},
  {"id": "bocadillo_guayaba_levapan", "n": "Bocadillo de Guayaba Levapan", "c": "especias", "f": "3 x 4,2 kg", "d": "Bocadillo de guayaba Levapan, formato industrial.", "img": "img/bocadillo_guayaba_levapan.jpg"},
  {"id": "canela_rama_kunatai", "n": "Canela en Rama Kuñataí", "c": "especias", "f": "50 g", "d": "Canela en rama Kuñataí.", "img": "img/canela_rama_kunatai.jpg"},
  {"id": "cedron_kunatai", "n": "Cedrón Kuñataí", "c": "especias", "f": "6 x 20 g", "d": "Hojas de cedrón Kuñataí.", "img": "img/cedron_kunatai.jpg"},
  {"id": "eucalipto_kunatai", "n": "Eucalipto Kuñataí", "c": "especias", "f": "6 x 40 g", "d": "Hojas de eucalipto Kuñataí.", "img": "img/eucalipto_kunatai.jpg"},
  {"id": "flor_jamaica_kunatai", "n": "Flor de Jamaica Kuñataí", "c": "especias", "f": "6 x 50 g", "d": "Flor de Jamaica Kuñataí.", "img": "img/flor_jamaica_kunatai.jpg"},
  {"id": "ruda_kunatai", "n": "Ruda Kuñataí", "c": "especias", "f": "6 x 20 g", "d": "Ruda Kuñataí.", "img": "img/ruda_kunatai.jpg"},
  {"id": "stevia_kunatai", "n": "Stevia Kuñataí", "c": "especias", "f": "6 x 20 g", "d": "Hojas de stevia Kuñataí.", "img": "img/stevia_kunatai.jpg"},
  {"id": "ajenjo_kunatai", "n": "Ajenjo Planta Kuñataí", "c": "especias", "f": "6 x 30 g", "d": "Ajenjo en planta Kuñataí.", "img": "img/ajenjo_kunatai.jpg"},
  {"id": "ajinomoto", "n": "Ajinomoto", "c": "especias", "f": "12 x 250 g", "d": "Glutamato monosódico Ajinomoto.", "img": "img/ajinomoto.jpg"},
  {"id": "cocido_alborada", "n": "Cocido Tradicional Instantáneo La Alborada", "c": "especias", "f": "Display 5 x 80 g", "d": "Mate cocido instantáneo La Alborada.", "img": "img/cocido_alborada.jpg"},
  {"id": "manzanilla_dulce_kunatai", "n": "Manzanilla Dulce Kuñataí", "c": "especias", "f": "6 x 20 g", "d": "Manzanilla dulce Kuñataí.", "img": "img/manzanilla_dulce_kunatai.jpg"},
  {"id": "cocido_kurupi", "n": "Mate Cocido Kurupí", "c": "especias", "f": "25 saq. x 12 g", "d": "Mate cocido Kurupí en saquitos.", "img": "img/cocido_kurupi.jpg"},
  {"id": "cocido_potex_dulcesar", "n": "Mate Cocido Potex Dulcesar", "c": "especias", "f": "12 x 150 g", "d": "Mate cocido Potex Dulcesar.", "img": "img/cocido_potex_dulcesar.jpg"},
  {"id": "plan30_te_guarani", "n": "Plan 30 Días Té Guaraní", "c": "especias", "f": "12 x 180 g", "d": "Té Guaraní Plan 30 Días.", "img": "img/plan30_te_guarani.jpg"},
  {"id": "sal_condimentada_dulcesar", "n": "Sal Condimentada Dulcesar", "c": "especias", "f": "400 g", "d": "Sal condimentada Dulcesar.", "img": "img/sal_condimentada_dulcesar.jpg"},
  {"id": "sal_condimentada_arcoiris", "n": "Sal Condimentada Arcoiris", "c": "especias", "f": "400 g", "d": "Sal condimentada Arcoiris.", "img": "img/sal_condimentada_arcoiris.jpg"},
  {"id": "te_guarani_adelgazate", "n": "Té Guaraní Adelgázate", "c": "especias", "f": "Display 12 x 3 g", "d": "Té Guaraní Adelgázate en saquitos.", "img": "img/te_guarani_adelgazate.jpg"},
  {"id": "cola_caballo_kunatai", "n": "Cola de Caballo Kuñataí", "c": "especias", "f": "40 g", "d": "Cola de caballo Kuñataí.", "img": "img/sin-foto.jpg"},
  {"id": "eneldo_kunatai", "n": "Eneldo Kuñataí", "c": "especias", "f": "6 x 20 g", "d": "Eneldo Kuñataí.", "img": "img/sin-foto.jpg"},
  {"id": "hierbaluisa_kunatai", "n": "Hierbaluisa Kuñataí", "c": "especias", "f": "6 x 50 g", "d": "Hierbaluisa Kuñataí.", "img": "img/sin-foto.jpg"},
  {"id": "jengibre_molido_kunatai", "n": "Jengibre Molido Kuñataí", "c": "especias", "f": "Paquete", "d": "Jengibre molido Kuñataí.", "img": "img/sin-foto.jpg"},
  {"id": "laurel_kunatai", "n": "Laurel en Hoja Kuñataí", "c": "especias", "f": "15 g", "d": "Hojas de laurel Kuñataí.", "img": "img/sin-foto.jpg"},
  {"id": "romero_kunatai", "n": "Romero Kuñataí", "c": "especias", "f": "6 x 30 g", "d": "Romero Kuñataí.", "img": "img/sin-foto.jpg"},
  {"id": "salvia_kunatai", "n": "Salvia Kuñataí", "c": "especias", "f": "6 x 20 g", "d": "Salvia Kuñataí.", "img": "img/sin-foto.jpg"},
  {"id": "sen_hojas_kunatai", "n": "Sen en Hojas Kuñataí", "c": "especias", "f": "6 x 20 g", "d": "Hojas de sen Kuñataí.", "img": "img/sin-foto.jpg"},
  {"id": "malva_kunatai", "n": "Malva Kuñataí", "c": "especias", "f": "6 x 30 g", "d": "Malva Kuñataí.", "img": "img/sin-foto.jpg"},
  {"id": "mandioca_congelada_b", "n": "Mandioca Congelada B", "c": "especias", "f": "Caja 25 kg", "d": "Mandioca (yuca) congelada.", "img": "img/sin-foto.jpg"},
  {"id": "mandioca_congelada_l", "n": "Mandioca Congelada L", "c": "especias", "f": "Caja 25 kg", "d": "Mandioca (yuca) congelada.", "img": "img/sin-foto.jpg"},
  {"id": "menta_kunatai", "n": "Menta Kuñataí", "c": "especias", "f": "6 x 20 g", "d": "Menta Kuñataí.", "img": "img/sin-foto.jpg"},
  {"id": "menta_chao", "n": "Menta Chao", "c": "especias", "f": "24 x 100 uds.", "d": "Caramelos de menta Chao.", "img": "img/sin-foto.jpg"},
  {"id": "aji_nativo_200ml", "n": "Salsa de Ají Nativo", "c": "salsas", "f": "24 x 200 ml", "d": "Salsa de ají picante Nativo.", "img": "img/aji_nativo_200ml.jpg"},
  {"id": "aji_nativo_100ml", "n": "Salsa de Ají Nativo", "c": "salsas", "f": "48 x 100 ml", "d": "Salsa de ají picante Nativo.", "img": "img/aji_nativo_100ml.jpg"},
  {"id": "aji_la_latina_100ml", "n": "Salsa de Ají Picante La Latina", "c": "salsas", "f": "100 ml", "d": "Salsa de ají picante La Latina.", "img": "img/aji_la_latina_100ml.jpg"},
  {"id": "aji_la_latina_200ml", "n": "Salsa de Ají Picante La Latina", "c": "salsas", "f": "200 ml", "d": "Salsa de ají picante La Latina.", "img": "img/aji_la_latina_200ml.jpg"},
  {"id": "aji_oriental_200ml", "n": "Salsa de Ají Picante Oriental", "c": "salsas", "f": "24 x 200 ml", "d": "Salsa de ají picante Oriental.", "img": "img/aji_oriental_200ml.jpg"},
  {"id": "aji_oriental_100ml", "n": "Salsa de Ají Picante Oriental", "c": "salsas", "f": "48 x 100 ml", "d": "Salsa de ají picante Oriental.", "img": "img/aji_oriental_100ml.jpg"},
  {"id": "soja_la_latina_100ml", "n": "Salsa China de Soja La Latina", "c": "salsas", "f": "100 ml", "d": "Salsa de soja La Latina (Ecuador).", "img": "img/soja_la_latina_100ml.jpg"},
  {"id": "soja_la_latina_200ml", "n": "Salsa China de Soja La Latina", "c": "salsas", "f": "200 ml", "d": "Salsa de soja La Latina (Ecuador).", "img": "img/soja_la_latina_200ml.jpg"},
  {"id": "soja_oriental_200ml", "n": "Salsa China de Soja Oriental", "c": "salsas", "f": "24 x 200 ml", "d": "Salsa de soja Oriental.", "img": "img/soja_oriental_200ml.jpg"},
  {"id": "soja_nativo_200ml", "n": "Salsa China Nativo", "c": "salsas", "f": "24 x 200 ml", "d": "Salsa china de soja Nativo.", "img": "img/soja_nativo_200ml.jpg"},
  {"id": "soja_nativo_100ml", "n": "Salsa China Nativo", "c": "salsas", "f": "48 x 100 ml", "d": "Salsa china de soja Nativo.", "img": "img/soja_nativo_100ml.jpg"},
  {"id": "salsa_picante_arcoiris", "n": "Salsa Picante Arcoiris", "c": "salsas", "f": "150 ml", "d": "Salsa picante Arcoiris.", "img": "img/salsa_picante_arcoiris.jpg"},
  {"id": "amor_wafer_vainilla", "n": "Amor Wafer Vainilla", "c": "dulces", "f": "Paquete", "d": "Galletas wafer Amor sabor vainilla.", "img": "img/amor_wafer_vainilla.jpg"},
  {"id": "amor_wafer_naranja", "n": "Amor Wafer Naranja", "c": "dulces", "f": "Paquete", "d": "Galletas wafer Amor sabor naranja.", "img": "img/amor_wafer_naranja.jpg"},
  {"id": "amor_wafer_classic", "n": "Amor Wafer Classic Original", "c": "dulces", "f": "Paquete", "d": "Galletas wafer Amor Classic.", "img": "img/amor_wafer_classic.jpg"},
  {"id": "amor_bagley", "n": "Amor Bagley", "c": "dulces", "f": "36 x 112 g", "d": "Galletitas Amor Bagley.", "img": "img/amor_bagley.jpg"},
  {"id": "amor_wafer_chocolate", "n": "Amor Wafer Chocolate", "c": "dulces", "f": "Paquete", "d": "Galletas wafer Amor sabor chocolate.", "img": "img/amor_wafer_chocolate.jpg"},
  {"id": "amor_wafer_limon", "n": "Amor Wafer Limón", "c": "dulces", "f": "Paquete", "d": "Galletas wafer Amor sabor limón.", "img": "img/amor_wafer_limon.jpg"},
  {"id": "amor_wafer_fresa", "n": "Amor Wafer Fresa", "c": "dulces", "f": "Paquete", "d": "Galletas wafer Amor sabor fresa.", "img": "img/amor_wafer_fresa.jpg"},
  {"id": "bonobon_blanco", "n": "Bon o Bon Blanco Arcor", "c": "dulces", "f": "450 g", "d": "Bombones Bon o Bon blancos Arcor.", "img": "img/bonobon_blanco.jpg"},
  {"id": "bonobon_negro", "n": "Bon o Bon Negro Arcor", "c": "dulces", "f": "450 g", "d": "Bombones Bon o Bon de chocolate Arcor.", "img": "img/bonobon_negro.jpg"},
  {"id": "barrilete", "n": "Barrilete", "c": "dulces", "f": "18 x 50 uds.", "d": "Caramelos Barrilete.", "img": "img/barrilete.jpg"},
  {"id": "bombon_barrilete", "n": "Bombón Barrilete", "c": "dulces", "f": "15 x 24 uds.", "d": "Bombón Barrilete.", "img": "img/bombon_barrilete.jpg"},
  {"id": "galletitas_tippy", "n": "Galletitas Tippy", "c": "dulces", "f": "10 x 180 g", "d": "Galletitas Tippy.", "img": "img/galletitas_tippy.jpg"},
  {"id": "bonbonbum_surtido", "n": "Bon Bon Bum Surtido", "c": "dulces", "f": "10 x 48 uds.", "d": "Chupetines Bon Bon Bum surtidos.", "img": "img/bonbonbum_surtido.jpg"},
  {"id": "turron_supercoco", "n": "Turrón Supercoco", "c": "dulces", "f": "36 x 50 uds.", "d": "Turrón de coco Supercoco.", "img": "img/turron_supercoco.jpg"},
  {"id": "turron_mani_arcor", "n": "Turrón de Maní Arcor", "c": "dulces", "f": "20 x 10 uds. x 25 g", "d": "Turrón de maní Arcor.", "img": "img/turron_mani_arcor.jpg"},
  {"id": "bombonera_guayaba_castipan", "n": "Bombonera Pasta de Guayaba Castipan", "c": "dulces", "f": "Frasco x 6", "d": "Pasta de guayaba Castipan en bombonera.", "img": "img/bombonera_guayaba_castipan.jpg"},
  {"id": "lonja_guayaba_castipan", "n": "Lonja de Guayaba Castipan", "c": "dulces", "f": "12 x 500 g", "d": "Lonja de guayaba Castipan.", "img": "img/lonja_guayaba_castipan.jpg"},
  {"id": "chocoramo", "n": "Chocoramo", "c": "dulces", "f": "20 uds.", "d": "Ponqué cubierto de chocolate Chocoramo.", "img": "img/chocoramo.jpg"},
  {"id": "cocosette", "n": "Cocosette Colombia", "c": "dulces", "f": "Display 21 x 250 g", "d": "Galleta wafer con coco Cocosette.", "img": "img/cocosette.jpg"},
  {"id": "dulce_leche_familiar_la_mulata", "n": "Dulce de Leche Familiar La Mulata", "c": "dulces", "f": "10 x 420 g", "d": "Dulce de leche familiar La Mulata.", "img": "img/dulce_leche_familiar_la_mulata.jpg"},
  {"id": "dulce_leche_heladero_la_mulata", "n": "Dulce de Leche Heladero La Mulata", "c": "dulces", "f": "2 x 7 kg", "d": "Dulce de leche para heladería La Mulata.", "img": "img/dulce_leche_heladero_la_mulata.jpg"},
  {"id": "dulce_leche_repostero_la_mulata_7kg", "n": "Dulce de Leche Repostero La Mulata", "c": "dulces", "f": "2 x 7 kg", "d": "Dulce de leche repostero La Mulata.", "img": "img/dulce_leche_repostero_la_mulata_7kg.jpg"},
  {"id": "dulce_leche_repostero_la_mulata_1kg", "n": "Dulce de Leche Repostero La Mulata", "c": "dulces", "f": "1 kg", "d": "Dulce de leche repostero La Mulata.", "img": "img/dulce_leche_repostero_la_mulata_1kg.jpg"},
  {"id": "dulce_leche_la_latina", "n": "Dulce de Leche La Latina", "c": "dulces", "f": "250 g", "d": "Dulce de leche La Latina.", "img": "img/dulce_leche_la_latina.jpg"},
  {"id": "mermelada_guayaba_facundo", "n": "Mermelada de Guayaba Facundo", "c": "dulces", "f": "300 g", "d": "Mermelada de guayaba Facundo.", "img": "img/mermelada_guayaba_facundo.jpg"},
  {"id": "menta_helada", "n": "Menta Helada", "c": "dulces", "f": "24 x 100 uds.", "d": "Caramelos Menta Helada.", "img": "img/menta_helada.jpg"},
  {"id": "mermelada_cristal_guayaba", "n": "Mermelada Cristal Guayaba Sabores de Areguá", "c": "dulces", "f": "410 g", "d": "Mermelada cristal de guayaba.", "img": "img/mermelada_cristal_guayaba.jpg"},
  {"id": "mermelada_guayaba_bote_250g", "n": "Mermelada de Guayaba Sabores de Areguá", "c": "dulces", "f": "Bote 250 g", "d": "Mermelada de guayaba en bote.", "img": "img/mermelada_guayaba_bote_250g.jpg"},
  {"id": "mermelada_cristal_guayaba_light", "n": "Mermelada Cristal Guayaba Light Sabores de Areguá", "c": "dulces", "f": "400 g", "d": "Mermelada cristal de guayaba light.", "img": "img/mermelada_cristal_guayaba_light.jpg"},
  {"id": "mermelada_cristal_mora", "n": "Mermelada Cristal Mora Sabores de Areguá", "c": "dulces", "f": "410 g", "d": "Mermelada cristal de mora.", "img": "img/mermelada_cristal_mora.jpg"},
  {"id": "mermelada_guayaba_bote_500g", "n": "Mermelada de Guayaba Sabores de Areguá", "c": "dulces", "f": "Bote 500 g", "d": "Mermelada de guayaba en bote.", "img": "img/mermelada_guayaba_bote_500g.jpg"},
  {"id": "mermelada_guayaba_bote_650g", "n": "Mermelada de Guayaba Sabores de Areguá", "c": "dulces", "f": "Bote 650 g", "d": "Mermelada de guayaba en bote.", "img": "img/mermelada_guayaba_bote_650g.jpg"},
  {"id": "panela_bloque_redonda", "n": "Panela Bloque Redonda El Dorado", "c": "dulces", "f": "454 g", "d": "Panela en bloque redondo El Dorado.", "img": "img/panela_bloque_redonda.jpg"},
  {"id": "panela_fraccionada", "n": "Panela Fraccionada El Dorado", "c": "dulces", "f": "454 g", "d": "Panela fraccionada El Dorado.", "img": "img/panela_fraccionada.jpg"},
  {"id": "panela_pulverizada", "n": "Panela Pulverizada", "c": "dulces", "f": "24 x 454 g", "d": "Panela pulverizada.", "img": "img/panela_pulverizada.jpg"},
  {"id": "panela_el_dorado_410g", "n": "Panela El Dorado", "c": "dulces", "f": "410 g", "d": "Panela El Dorado.", "img": "img/panela_el_dorado_410g.jpg"},
  {"id": "panelin_fraccionada", "n": "Panelín Fraccionada El Dorado", "c": "dulces", "f": "24 x 454 g", "d": "Panelín fraccionada El Dorado.", "img": "img/panelin_fraccionada.jpg"},
  {"id": "pasta_cacahuete_darachide", "n": "Pasta de Cacahuete Darachide", "c": "dulces", "f": "500 g", "d": "Pasta de cacahuete Darachide.", "img": "img/pasta_cacahuete_darachide.jpg"},
  {"id": "pasta_cacahuete_darachide_sin_azucar", "n": "Pasta de Cacahuete sin Azúcar Darachide", "c": "dulces", "f": "500 g", "d": "Pasta de cacahuete sin azúcar Darachide.", "img": "img/pasta_cacahuete_darachide_sin_azucar.jpg"},
  {"id": "pasta_guayaba_predilecta_300g", "n": "Pasta de Guayaba Amore Predilecta", "c": "dulces", "f": "300 g", "d": "Pasta de guayaba (goiabada) Predilecta.", "img": "img/pasta_guayaba_predilecta_300g.jpg"},
  {"id": "pasta_guayaba_predilecta_600g", "n": "Pasta de Guayaba Amore Predilecta", "c": "dulces", "f": "600 g", "d": "Pasta de guayaba (goiabada) Predilecta.", "img": "img/pasta_guayaba_predilecta_600g.jpg"},
  {"id": "pasta_guayaba_goya", "n": "Pasta de Guayaba Goya (lata)", "c": "dulces", "f": "12 x 595 g", "d": "Pasta de guayaba Goya en lata.", "img": "img/pasta_guayaba_goya.jpg"},
  {"id": "miel_cana_3_hermanas", "n": "Miel de Caña 3 Hermanas", "c": "dulces", "f": "Botella", "d": "Miel de caña 3 Hermanas.", "img": "img/miel_cana_3_hermanas.jpg"},
  {"id": "bonbonbum_tarro_caramelo", "n": "Bon Bon Bum Tarro Caramelo", "c": "dulces", "f": "Tarro", "d": "Chupetines Bon Bon Bum en tarro.", "img": "img/sin-foto.jpg"},
  {"id": "dulce_leche_repostero_21kg", "n": "Dulce de Leche Repostero", "c": "dulces", "f": "Bote 21 kg", "d": "Dulce de leche repostero, formato industrial.", "img": "img/sin-foto.jpg"},
  {"id": "chuno_blanco", "n": "Chuño Blanco", "c": "dulces", "f": "24 x 500 g", "d": "Chuño blanco (papa deshidratada).", "img": "img/sin-foto.jpg"},
  {"id": "chuno_negro", "n": "Chuño Negro", "c": "dulces", "f": "24 x 500 g", "d": "Chuño negro (papa deshidratada).", "img": "img/sin-foto.jpg"},
  {"id": "dulce_guayaba_repostero_25kg", "n": "Dulce de Guayaba Repostero Sabores de Areguá", "c": "dulces", "f": "25 kg", "d": "Dulce de guayaba repostero, formato industrial.", "img": "img/sin-foto.jpg"},
  {"id": "mani_pelado", "n": "Maní Pelado", "c": "frutos", "f": "24 x 500 g", "d": "Maní pelado.", "img": "img/mani_pelado.jpg"},
  {"id": "kai_ladrillo_entero_200g", "n": "Ka'i Ladrillo Entero Sabores de Areguá", "c": "frutos", "f": "200 g", "d": "Dulce de maní Ka'i Ladrillo, entero.", "img": "img/kai_ladrillo_entero_200g.jpg"},
  {"id": "kai_ladrillo_entero_400g", "n": "Ka'i Ladrillo Entero Sabores de Areguá", "c": "frutos", "f": "400 g", "d": "Dulce de maní Ka'i Ladrillo, entero.", "img": "img/kai_ladrillo_entero_400g.jpg"},
  {"id": "kai_ladrillo_molido_200g", "n": "Ka'i Ladrillo Molido Sabores de Areguá", "c": "frutos", "f": "200 g", "d": "Dulce de maní Ka'i Ladrillo, molido.", "img": "img/kai_ladrillo_molido_200g.jpg"},
  {"id": "kai_ladrillo_molido_400g", "n": "Ka'i Ladrillo Molido Sabores de Areguá", "c": "frutos", "f": "400 g", "d": "Dulce de maní Ka'i Ladrillo, molido.", "img": "img/kai_ladrillo_molido_400g.jpg"},
  {"id": "mani_molido_barrerena", "n": "Maní Molido La Barrereña", "c": "frutos", "f": "8 x 350 g", "d": "Maní molido La Barrereña.", "img": "img/sin-foto.jpg"},
  {"id": "manteca_mani_barrerena", "n": "Manteca de Maní La Barrereña", "c": "frutos", "f": "12 x 400 g", "d": "Manteca de maní La Barrereña.", "img": "img/sin-foto.jpg"},
  {"id": "bombilla_corta_kunatai", "n": "Bombilla Corta Kuñataí", "c": "menaje", "f": "Unidad", "d": "Bombilla corta para mate o tereré.", "img": "img/bombilla_corta_kunatai.jpg"},
  {"id": "bombilla_larga_kunatai", "n": "Bombilla Larga Kuñataí", "c": "menaje", "f": "Unidad", "d": "Bombilla larga para mate o tereré.", "img": "img/bombilla_larga_kunatai.jpg"},
];
